// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package executor

func addintAndfloat32(a int, b float32) float32 {
	return float32(a) + b
}

func substractintAndfloat32(a int, b float32) float32 {
	return float32(a) - b
}

func divintAndfloat32(a int, b float32) float32 {
	return float32(a) / b
}

func multiplyintAndfloat32(a int, b float32) float32 {
	return float32(a) * b
}

func lessThanintAndfloat32(a int, b float32) bool {
	return float32(a) < b
}

func lessOrEqualintAndfloat32(a int, b float32) bool {
	return float32(a) <= b
}

func greaterThanintAndfloat32(a int, b float32) bool {
	return float32(a) > b
}

func greaterOrEqualintAndfloat32(a int, b float32) bool {
	return float32(a) >= b
}

func equalintAndfloat32(a int, b float32) bool {
	return float32(a) == b
}

func notEqualintAndfloat32(a int, b float32) bool {
	return float32(a) != b
}

var _ = addMathFunc("add", addintAndfloat32)
var _ = addMathFunc("substract", substractintAndfloat32)
var _ = addMathFunc("div", divintAndfloat32)
var _ = addMathFunc("mul", multiplyintAndfloat32)
var _ = addMathFunc("lt", lessThanintAndfloat32)
var _ = addMathFunc("lte", lessOrEqualintAndfloat32)
var _ = addMathFunc("gt", greaterThanintAndfloat32)
var _ = addMathFunc("gte", greaterOrEqualintAndfloat32)
var _ = addMathFunc("eq", equalintAndfloat32)
var _ = addMathFunc("ne", notEqualintAndfloat32)

func addintAndfloat64(a int, b float64) float64 {
	return float64(a) + b
}

func substractintAndfloat64(a int, b float64) float64 {
	return float64(a) - b
}

func divintAndfloat64(a int, b float64) float64 {
	return float64(a) / b
}

func multiplyintAndfloat64(a int, b float64) float64 {
	return float64(a) * b
}

func lessThanintAndfloat64(a int, b float64) bool {
	return float64(a) < b
}

func lessOrEqualintAndfloat64(a int, b float64) bool {
	return float64(a) <= b
}

func greaterThanintAndfloat64(a int, b float64) bool {
	return float64(a) > b
}

func greaterOrEqualintAndfloat64(a int, b float64) bool {
	return float64(a) >= b
}

func equalintAndfloat64(a int, b float64) bool {
	return float64(a) == b
}

func notEqualintAndfloat64(a int, b float64) bool {
	return float64(a) != b
}

var _ = addMathFunc("add", addintAndfloat64)
var _ = addMathFunc("substract", substractintAndfloat64)
var _ = addMathFunc("div", divintAndfloat64)
var _ = addMathFunc("mul", multiplyintAndfloat64)
var _ = addMathFunc("lt", lessThanintAndfloat64)
var _ = addMathFunc("lte", lessOrEqualintAndfloat64)
var _ = addMathFunc("gt", greaterThanintAndfloat64)
var _ = addMathFunc("gte", greaterOrEqualintAndfloat64)
var _ = addMathFunc("eq", equalintAndfloat64)
var _ = addMathFunc("ne", notEqualintAndfloat64)

func addint32Andfloat32(a int32, b float32) float32 {
	return float32(a) + b
}

func substractint32Andfloat32(a int32, b float32) float32 {
	return float32(a) - b
}

func divint32Andfloat32(a int32, b float32) float32 {
	return float32(a) / b
}

func multiplyint32Andfloat32(a int32, b float32) float32 {
	return float32(a) * b
}

func lessThanint32Andfloat32(a int32, b float32) bool {
	return float32(a) < b
}

func lessOrEqualint32Andfloat32(a int32, b float32) bool {
	return float32(a) <= b
}

func greaterThanint32Andfloat32(a int32, b float32) bool {
	return float32(a) > b
}

func greaterOrEqualint32Andfloat32(a int32, b float32) bool {
	return float32(a) >= b
}

func equalint32Andfloat32(a int32, b float32) bool {
	return float32(a) == b
}

func notEqualint32Andfloat32(a int32, b float32) bool {
	return float32(a) != b
}

var _ = addMathFunc("add", addint32Andfloat32)
var _ = addMathFunc("substract", substractint32Andfloat32)
var _ = addMathFunc("div", divint32Andfloat32)
var _ = addMathFunc("mul", multiplyint32Andfloat32)
var _ = addMathFunc("lt", lessThanint32Andfloat32)
var _ = addMathFunc("lte", lessOrEqualint32Andfloat32)
var _ = addMathFunc("gt", greaterThanint32Andfloat32)
var _ = addMathFunc("gte", greaterOrEqualint32Andfloat32)
var _ = addMathFunc("eq", equalint32Andfloat32)
var _ = addMathFunc("ne", notEqualint32Andfloat32)

func addint32Andfloat64(a int32, b float64) float64 {
	return float64(a) + b
}

func substractint32Andfloat64(a int32, b float64) float64 {
	return float64(a) - b
}

func divint32Andfloat64(a int32, b float64) float64 {
	return float64(a) / b
}

func multiplyint32Andfloat64(a int32, b float64) float64 {
	return float64(a) * b
}

func lessThanint32Andfloat64(a int32, b float64) bool {
	return float64(a) < b
}

func lessOrEqualint32Andfloat64(a int32, b float64) bool {
	return float64(a) <= b
}

func greaterThanint32Andfloat64(a int32, b float64) bool {
	return float64(a) > b
}

func greaterOrEqualint32Andfloat64(a int32, b float64) bool {
	return float64(a) >= b
}

func equalint32Andfloat64(a int32, b float64) bool {
	return float64(a) == b
}

func notEqualint32Andfloat64(a int32, b float64) bool {
	return float64(a) != b
}

var _ = addMathFunc("add", addint32Andfloat64)
var _ = addMathFunc("substract", substractint32Andfloat64)
var _ = addMathFunc("div", divint32Andfloat64)
var _ = addMathFunc("mul", multiplyint32Andfloat64)
var _ = addMathFunc("lt", lessThanint32Andfloat64)
var _ = addMathFunc("lte", lessOrEqualint32Andfloat64)
var _ = addMathFunc("gt", greaterThanint32Andfloat64)
var _ = addMathFunc("gte", greaterOrEqualint32Andfloat64)
var _ = addMathFunc("eq", equalint32Andfloat64)
var _ = addMathFunc("ne", notEqualint32Andfloat64)

func addfloat32Andfloat32(a float32, b float32) float32 {
	return float32(a) + b
}

func substractfloat32Andfloat32(a float32, b float32) float32 {
	return float32(a) - b
}

func divfloat32Andfloat32(a float32, b float32) float32 {
	return float32(a) / b
}

func multiplyfloat32Andfloat32(a float32, b float32) float32 {
	return float32(a) * b
}

func lessThanfloat32Andfloat32(a float32, b float32) bool {
	return float32(a) < b
}

func lessOrEqualfloat32Andfloat32(a float32, b float32) bool {
	return float32(a) <= b
}

func greaterThanfloat32Andfloat32(a float32, b float32) bool {
	return float32(a) > b
}

func greaterOrEqualfloat32Andfloat32(a float32, b float32) bool {
	return float32(a) >= b
}

func equalfloat32Andfloat32(a float32, b float32) bool {
	return float32(a) == b
}

func notEqualfloat32Andfloat32(a float32, b float32) bool {
	return float32(a) != b
}

var _ = addMathFunc("add", addfloat32Andfloat32)
var _ = addMathFunc("substract", substractfloat32Andfloat32)
var _ = addMathFunc("div", divfloat32Andfloat32)
var _ = addMathFunc("mul", multiplyfloat32Andfloat32)
var _ = addMathFunc("lt", lessThanfloat32Andfloat32)
var _ = addMathFunc("lte", lessOrEqualfloat32Andfloat32)
var _ = addMathFunc("gt", greaterThanfloat32Andfloat32)
var _ = addMathFunc("gte", greaterOrEqualfloat32Andfloat32)
var _ = addMathFunc("eq", equalfloat32Andfloat32)
var _ = addMathFunc("ne", notEqualfloat32Andfloat32)

func addfloat32Andfloat64(a float32, b float64) float64 {
	return float64(a) + b
}

func substractfloat32Andfloat64(a float32, b float64) float64 {
	return float64(a) - b
}

func divfloat32Andfloat64(a float32, b float64) float64 {
	return float64(a) / b
}

func multiplyfloat32Andfloat64(a float32, b float64) float64 {
	return float64(a) * b
}

func lessThanfloat32Andfloat64(a float32, b float64) bool {
	return float64(a) < b
}

func lessOrEqualfloat32Andfloat64(a float32, b float64) bool {
	return float64(a) <= b
}

func greaterThanfloat32Andfloat64(a float32, b float64) bool {
	return float64(a) > b
}

func greaterOrEqualfloat32Andfloat64(a float32, b float64) bool {
	return float64(a) >= b
}

func equalfloat32Andfloat64(a float32, b float64) bool {
	return float64(a) == b
}

func notEqualfloat32Andfloat64(a float32, b float64) bool {
	return float64(a) != b
}

var _ = addMathFunc("add", addfloat32Andfloat64)
var _ = addMathFunc("substract", substractfloat32Andfloat64)
var _ = addMathFunc("div", divfloat32Andfloat64)
var _ = addMathFunc("mul", multiplyfloat32Andfloat64)
var _ = addMathFunc("lt", lessThanfloat32Andfloat64)
var _ = addMathFunc("lte", lessOrEqualfloat32Andfloat64)
var _ = addMathFunc("gt", greaterThanfloat32Andfloat64)
var _ = addMathFunc("gte", greaterOrEqualfloat32Andfloat64)
var _ = addMathFunc("eq", equalfloat32Andfloat64)
var _ = addMathFunc("ne", notEqualfloat32Andfloat64)

func addfloat64Andfloat32(a float64, b float32) float32 {
	return float32(a) + b
}

func substractfloat64Andfloat32(a float64, b float32) float32 {
	return float32(a) - b
}

func divfloat64Andfloat32(a float64, b float32) float32 {
	return float32(a) / b
}

func multiplyfloat64Andfloat32(a float64, b float32) float32 {
	return float32(a) * b
}

func lessThanfloat64Andfloat32(a float64, b float32) bool {
	return float32(a) < b
}

func lessOrEqualfloat64Andfloat32(a float64, b float32) bool {
	return float32(a) <= b
}

func greaterThanfloat64Andfloat32(a float64, b float32) bool {
	return float32(a) > b
}

func greaterOrEqualfloat64Andfloat32(a float64, b float32) bool {
	return float32(a) >= b
}

func equalfloat64Andfloat32(a float64, b float32) bool {
	return float32(a) == b
}

func notEqualfloat64Andfloat32(a float64, b float32) bool {
	return float32(a) != b
}

var _ = addMathFunc("add", addfloat64Andfloat32)
var _ = addMathFunc("substract", substractfloat64Andfloat32)
var _ = addMathFunc("div", divfloat64Andfloat32)
var _ = addMathFunc("mul", multiplyfloat64Andfloat32)
var _ = addMathFunc("lt", lessThanfloat64Andfloat32)
var _ = addMathFunc("lte", lessOrEqualfloat64Andfloat32)
var _ = addMathFunc("gt", greaterThanfloat64Andfloat32)
var _ = addMathFunc("gte", greaterOrEqualfloat64Andfloat32)
var _ = addMathFunc("eq", equalfloat64Andfloat32)
var _ = addMathFunc("ne", notEqualfloat64Andfloat32)

func addfloat64Andfloat64(a float64, b float64) float64 {
	return float64(a) + b
}

func substractfloat64Andfloat64(a float64, b float64) float64 {
	return float64(a) - b
}

func divfloat64Andfloat64(a float64, b float64) float64 {
	return float64(a) / b
}

func multiplyfloat64Andfloat64(a float64, b float64) float64 {
	return float64(a) * b
}

func lessThanfloat64Andfloat64(a float64, b float64) bool {
	return float64(a) < b
}

func lessOrEqualfloat64Andfloat64(a float64, b float64) bool {
	return float64(a) <= b
}

func greaterThanfloat64Andfloat64(a float64, b float64) bool {
	return float64(a) > b
}

func greaterOrEqualfloat64Andfloat64(a float64, b float64) bool {
	return float64(a) >= b
}

func equalfloat64Andfloat64(a float64, b float64) bool {
	return float64(a) == b
}

func notEqualfloat64Andfloat64(a float64, b float64) bool {
	return float64(a) != b
}

var _ = addMathFunc("add", addfloat64Andfloat64)
var _ = addMathFunc("substract", substractfloat64Andfloat64)
var _ = addMathFunc("div", divfloat64Andfloat64)
var _ = addMathFunc("mul", multiplyfloat64Andfloat64)
var _ = addMathFunc("lt", lessThanfloat64Andfloat64)
var _ = addMathFunc("lte", lessOrEqualfloat64Andfloat64)
var _ = addMathFunc("gt", greaterThanfloat64Andfloat64)
var _ = addMathFunc("gte", greaterOrEqualfloat64Andfloat64)
var _ = addMathFunc("eq", equalfloat64Andfloat64)
var _ = addMathFunc("ne", notEqualfloat64Andfloat64)
